FROM python:3.12-slim-bookworm

WORKDIR /app
RUN apt-get update \
    && apt-get upgrade -y \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY simple_app ./simple_app
EXPOSE 8010
CMD ["uvicorn", "simple_app.main:app", "--host", "0.0.0.0", "--port", "8010"]
