sonar.organization=gouthamkumar4

sonar.projectKey=GouthamKumar4_Bayers_hackthon_dev
sonar.projectName=Bayers_hackthon_dev

sonar.sources=app
sonar.tests=tests

sonar.python.version=3.11

sonar.host.url=https://sonarcloud.io
sonar.qualitygate.wait=true

sonar.python.coverage.reportPaths=coverage.xml
