sonar.projectKey=gouthamkumar4
sonar.organization=Goutham Kumar
sonar.projectName=Bayers Hackthon Dev
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.11
sonar.qualitygate.wait=true
sonar.host.url=https://sonarcloud.io
sonar.token=bd4fff0489690622df9e5cb99af7347f16008f5e
